# Generated by Django 3.0.2 on 2020-01-17 09:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('summary_author', models.TextField(blank=True, max_length=5000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Mail'), ('F', 'Female')], default='M', max_length=10)),
                ('image', models.ImageField(blank=None, null=True, upload_to='static/author/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('language', models.CharField(blank=True, max_length=30, null=True)),
                ('ISBN', models.CharField(blank=None, max_length=13, null=True, verbose_name='ISBN')),
                ('add', models.DateField(auto_now_add=True)),
                ('modern', models.DateField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=None, null=True, upload_to='static/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Enter a genre', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('book_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('add_1', models.DateField(auto_now_add=True)),
                ('modern_1', models.DateField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', max_length=10)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Book')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genre'),
        ),
    ]
